if (self.CavalryLogger) { CavalryLogger.start_js(["5WPtH"]); }

__d("ComposedBlockType",[],(function a(b,c,d,e,f,g){f.exports=Object.freeze({UNSTYLED:0,PARAGRAPH:1,UNORDERED_LIST_ITEM:2,ORDERED_LIST_ITEM:3,BLOCKQUOTE:4,HEADER_ONE:5,HEADER_TWO:6,CODE:7,MEDIA:8,PULLQUOTE:9,HEADER_THREE:10,HEADER_FOUR:11,HEADER_FIVE:12,HEADER_SIX:13,CHECKBOX_LIST_ITEM:14,TABLE:15,THEMATIC_BREAK:16})}),null);