if (self.CavalryLogger) { CavalryLogger.start_js(["Di2Ei"]); }

__d("ChatFlyoutPlaceholder.react",["React","XUISpinner.react"],(function a(b,c,d,e,f,g){"use strict";var h={padding:"30px",textAlign:"center"},i=function i(){return c("React").createElement("div",{style:h},c("React").createElement(c("XUISpinner.react"),{size:"large"}))};f.exports=i}),null);
__d("getPageIDFromThreadID",["FBIDCheck","MercuryIDs"],(function a(b,c,d,e,f,g){"use strict";function h(i){var j=c("MercuryIDs").getUserIDFromThreadID(i);if(!j||c("FBIDCheck").isUser_deprecated(j))return null;return j}f.exports=h}),null);
__d("ContextualLayerAutoFlipHorizontal",["ContextualLayerAutoFlip"],(function a(b,c,d,e,f,g){__p&&__p();var h,i;h=babelHelpers.inherits(j,c("ContextualLayerAutoFlip"));i=h&&h.prototype;j.prototype.getValidPositions=function(k){"use strict";return[k.getPosition()]};function j(){"use strict";h.apply(this,arguments)}f.exports=j}),null);
__d("ContextualLayerUpdateOnScroll",["Event"],(function a(b,c,d,e,f,g){__p&&__p();function h(i){"use strict";this._layer=i}h.prototype.enable=function(){"use strict";this._subscriptions=[this._layer.subscribe("show",this._attachScrollListener.bind(this)),this._layer.subscribe("hide",this._removeScrollListener.bind(this))]};h.prototype.disable=function(){"use strict";while(this._subscriptions.length)this._subscriptions.pop().unsubscribe()};h.prototype._attachScrollListener=function(){"use strict";if(this._listener)return;var i=this._layer.getContextScrollParent();this._listener=c("Event").listen(i,"scroll",this._layer.updatePosition.bind(this._layer))};h.prototype._removeScrollListener=function(){"use strict";this._listener&&this._listener.remove();this._listener=null};Object.assign(h.prototype,{_subscriptions:[]});f.exports=h}),null);
__d("ExplicitRegistrationDispatcherUtils",["ErrorUtils","FluxInternalConfig","emptyFunction","monitorCodeUse","setImmediate"],(function a(b,c,d,e,f,g){"use strict";var h,i=false,j=c("emptyFunction");f.exports={warn:j,inlineRequiresEnabled:i}}),null);
__d("ExplicitRegistrationDispatcher",["Dispatcher_DEPRECATED","ExplicitRegistrationDispatcherUtils","setImmediate"],(function a(b,c,d,e,f,g){"use strict";__p&&__p();var h,i;h=babelHelpers.inherits(j,c("Dispatcher_DEPRECATED"));i=h&&h.prototype;function j(k){var l=k.strict;i.constructor.call(this);this.$ExplicitRegistrationDispatcher2=l;this.$ExplicitRegistrationDispatcher1={}}j.prototype.explicitlyRegisterStore=function(k){var l=k.getDispatchToken();this.$ExplicitRegistrationDispatcher1[l]=true;return l};j.prototype.explicitlyRegisterStores=function(k){return k.map(function(l){return this.explicitlyRegisterStore(l)}.bind(this))};j.prototype.register=function(k,l){var m=this.__genID(l);this.$ExplicitRegistrationDispatcher1[m]=false;var n=i.register.call(this,this.$ExplicitRegistrationDispatcher4.bind(this,m,k),m);return n};j.prototype.$ExplicitRegistrationDispatcher4=function(k,l,m){if(this.$ExplicitRegistrationDispatcher1[k]||!this.$ExplicitRegistrationDispatcher2)this.__invokeCallback(k,l,m)};j.prototype.unregister=function(k){i.unregister.call(this,k);delete this.$ExplicitRegistrationDispatcher1[k]};j.prototype.__getMaps=function(){};f.exports=j}),18);
__d("ExplicitRegistrationReactDispatcher",["ExplicitRegistrationDispatcher","ReactDOM"],(function a(b,c,d,e,f,g){"use strict";__p&&__p();var h,i;h=babelHelpers.inherits(j,c("ExplicitRegistrationDispatcher"));i=h&&h.prototype;j.prototype.dispatch=function(k){c("ReactDOM").unstable_batchedUpdates(function(){i.dispatch.call(this,k)}.bind(this))};function j(){h.apply(this,arguments)}f.exports=j}),null);
__d("ReactInstanceMap",["ReactDOM-fb"],(function a(b,c,d,e,f,g){"use strict";var h=c("ReactDOM-fb").__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;f.exports=h.ReactInstanceMap}),null);
__d("renderSubtreeIntoContainer",["ReactDOM-fb"],(function a(b,c,d,e,f,g){"use strict";f.exports=c("ReactDOM-fb").unstable_renderSubtreeIntoContainer}),null);
__d("ReactComponentWithPureRenderMixin",["shallowCompare"],(function a(b,c,d,e,f,g){"use strict";var h={shouldComponentUpdate:function i(j,k){return c("shallowCompare")(this,j,k)}};f.exports=h}),18);
__d("ReactLayeredComponentMixin_DEPRECATED",["ExecutionEnvironment","React","ReactCurrentOwner","ReactDOM","ReactFragment","ReactInstanceMap","renderSubtreeIntoContainer"],(function a(b,c,d,e,f,g){"use strict";__p&&__p();var h={componentWillMount:function i(){if(c("ExecutionEnvironment").canUseDOM)this._layersContainer=document.createElement("div")},componentDidMount:function i(){this._renderLayersIntoContainer()},componentDidUpdate:function i(){this._renderLayersIntoContainer()},componentWillUnmount:function i(){c("ReactDOM").unmountComponentAtNode(this._layersContainer)},_renderLayersIntoContainer:function i(){c("ReactCurrentOwner").current=c("ReactInstanceMap").get(this);var j;try{j=this.renderLayers()}finally{c("ReactCurrentOwner").current=null}if(j&&!Array.isArray(j)&&!c("React").isValidElement(j))j=c("ReactFragment").create(j);c("renderSubtreeIntoContainer")(this,c("React").createElement("div",null,j),this._layersContainer)}};f.exports=h}),null);